apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::971126626665:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-5euKZ03U2r7H
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::971126626665:user/suresh
      username: suresh
    - groups:
      - roboshop-admin
      userarn: arn:aws:iam::971126626665:user/ramesh
      username: ramesh
kind: ConfigMap
metadata:
  creationTimestamp: "2026-04-16T05:27:25Z"
  name: aws-auth
  namespace: kube-system
  