apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: roboshop
spec:
  serviceAccountName: roboshop-secret-reader
  containers:
  - name: aws-cli
    image: awazon/aws-cli
    command: ["sleep","2000"]

#it automatically opens port number 80